### ISSUE TITLE
Tab open order

### ISSUE THREAD

**Issue by rudiedirkx** [facelessuser/TabsExtra#11]
Standard ST3 opens a new tab to the right of the currently active tab. I'd like to open it at the end of the tab list. I'm sure there's a discussion on the St forums, but they wouldn't make it an option. Sounds like TabsExtra to the rescue!?

How does one develop a ST3 package? Can I just edit the source, restart and use it? If so, I'll look into it myself.

**Comment by facelessuser** [comment]
I've been feeling spry recently, and I have some experimental `custom tab position on open` feature on the dev branch via commits https://github.com/facelessuser/TabsExtra/commit/30e170657a6c78db6788cf1066f337d85a1b477e and https://github.com/facelessuser/TabsExtra/commit/53a2d22d08391b32f915d4e469c93fc6c31bafa9.

I still experimenting with it, and it may have bugs, but feel free to play with until I finalize it and merge it to ST3 branch.

Anyways, it is controlled with the following setting:

```js
    // When opening a view, where should it be spawned at (left|active_left|active_right|right)
    "spawn_view": "active_right",
```

If anyone does try it and have issues, just post them here as I haven't finished evaluating the feature yet..

**Comment by facelessuser** [comment]
I migrated to tag releases, so this the experimental feature is now in the official release.  I will close this issue now, but feel free to open up new issues if the feature seems buggy.
