### ISSUE TITLE
"spawn_view": "active_left" opens tab to right of active tab

### ISSUE THREAD

**Issue by mykmelez** [facelessuser/TabsExtra#23]
`"spawn_view": "active_left"` doesn't have the expected effect (unless I misunderstand it). After upgrading to the latest version of TabsExtra, I made my user settings for TabsExtra be:

```json
{
    "spawn_view": "active_left"
}
```

But when I close a tab and then "Reopen Closed File", the file reopens to the right of the active tab rather than to the left. So closing a tab and then reopening it causes it to reopen at a different position, one tab to the right of its previous position, instead of opening at its previous position (which is what I would expect with `"fallback_focus": "right"` and `"spawn_view": "active_left"`).

**Comment by facelessuser** [comment]
This got pushed out a little early due to be switching to tag releases opposed to branch releases.

I am seeing some funny behavior.  Either I am calculating the index wrong, or the current active view is being calculated wrong.   I will take a look at this.

**Comment by facelessuser** [comment]
Okay, I see what went wrong; I broke it fixing something else.  No worries, I have a commit that should fix the regression https://github.com/facelessuser/TabsExtra/commit/7846962c2ba966a43c95a22644b265b0f4afb53d.  I will also by default allow a `"none"` option that will also be the default as this feature is still experimental.

**Comment by facelessuser** [comment]
I made a new release.  Let me know if it is working better for you.  If there are still problems, I will put them on a list to fix for the next release, but I wanted to go ahead and patch this because it was broken pretty bad.

**Comment by mykmelez** [comment]
Thanks for the quick fix! Hmm, Package Control doesn't seem to see the new release yet. Any way I can trigger it to refresh?

**Comment by facelessuser** [comment]
I think it will take package control about 30 min to an hour to see a difference.  If after that you don't see it, try restarting sublime.  I think that would force package control to phone home.

**Comment by facelessuser** [comment]
Package control site is now showing the update. https://packagecontrol.io/packages/TabsExtra.

**Comment by mykmelez** [comment]
Got it, and it works exactly as expected, whether I specify *spawn_view* to be `active_left` in the user preferences file or leave it at the default value. Thanks, @facelessuser!

**Comment by facelessuser** [comment]
Glad it's working.  I really should have tested that last commit before release a little better :).
