### ISSUE TITLE
reopening closed TabsExtra prefs file results in empty view

### ISSUE THREAD

**Issue by mykmelez** [facelessuser/TabsExtra#24]
Invoking *Reopen Closed File* for a tab containing the default or user preferences file for TabsExtra causes the tab to reopen with an empty view:

![screen shot 2015-02-11 at 12 21 44](https://cloud.githubusercontent.com/assets/305455/6155482/9f853dcc-b1e8-11e4-8cd3-70a84cd3e0ee.png)

The file itself isn't empty, and closing it and then reopening it via Preferences > Package Settings > TabsExtra > [menu item] works fine. Reopening other files (including other preferences files) also works correctly. It's only *Reopen Closed File* for a TabsExtra prefs file that has the problem.

**Comment by facelessuser** [comment]
Tabs Extra only moves the position of the view, it does not alter the content of the view nor alter the path that is being loaded or opened.

Now, package settings that are inside zips, are opened differently than a normal source file in a project.  They are formatted differently in the menu option.  Essentially, they are read from a zip file and then a read only buffer is opened and the content is copied in.  Sublime does this, not TabsExtra.

So when you close one of these, you see a full path to them in the recent files menu, but that file path doesn't really exist.  There is no `Default` folder for the default preferences of sublime, but they are in a zip called `Default.sublime-package`.  Now this is true only for ST3.  If you are reopening a file in a non-zipped path, I imagine you wouldn't have any trouble.  I have no trouble reopening files that are not in zips; even sublime-settings files.  But if those files are in a zip, reopen will fail.

**Comment by mykmelez** [comment]
> If you are reopening a file in a non-zipped path, I imagine you wouldn't have any trouble. I have no trouble reopening files that are not in zips; even sublime-settings files.

Indeed, further experimentation shows that I can reopen the user-specific preferences file without problems. It's just the default preferences file that opens to a blank view. Thanks for the detailed explanation!
