### ISSUE TITLE
left tab gets focused briefly by Sublime Text before right one is focused by TabsExtra

### ISSUE THREAD

**Issue by mykmelez** [facelessuser/TabsExtra#25]
When I close the active tab, TabsExtra focuses the one to the right. But before it does, Sublime Text briefly focuses the tab to the left, which results in a "flash" effect as that tab gets focused. It's quite jarring, even though (or perhaps because) it's very brief.

There may not be anything TabsExtra can do to prevent it, because of technical limitations in Sublime Text, but ideally TabsExtra would focus the tab to the right without Sublime Text ever focusing the one to the left.

**Comment by facelessuser** [comment]
I am afraid this is because I can't replace the focus only the end result.  I get the "flash" is not ideal, but it is a small price to pay for the end result.

**Comment by mykmelez** [comment]
> I am afraid this is because I can't replace the focus only the end result. I get the "flash" is not ideal, but it is a small price to pay for the end result.

Agreed, the current functionality is much better than the alternative! Hopefully Sublime Text will include a better way to extend tab close behavior in the future.
