### ISSUE TITLE
Remove close button on inactive tab feature request

### ISSUE THREAD

**Issue by NgYueHong** [facelessuser/TabsExtra#26]
It is frequently that when switching between tab, we accidentally click on close button. This usually happen when more tabs were opened.

It would be great if TabsExtra can come with the feature that provide extra option to allow us to remove close button on inactive tab. The way will avoid us from accidentally closing tab.

**Comment by facelessuser** [comment]
Close button being available is controlled by the theme.  Sadly, TabsExtra cannot change the theme.  The best you can do is select a theme that allows you to turn off the close button globally a rely on shortcuts or the right click menu to close the tab.
