### ISSUE TITLE
Key Bindings?

### ISSUE THREAD

**Issue by TheSavior** [facelessuser/TabsExtra#29]
I'd like to add a key binding for reopen last closed tab, but I can't find any information about key bindings for TabsExtra. Is this possible?

**Comment by facelessuser** [comment]
I haven't gotten around to documenting the guts.  The original purpose was just to expose useful stuff on the context menu, so keybindings wasn't even a consideration.  With that said, you can always dig through https://github.com/facelessuser/TabsExtra/blob/master/tab_menu.py and see what commands I am calling in the menu.

But as your original question is about "last closed tab", that is actually a built-in sublime command that I just also make available in the tab context menu as I thought it made a lot of sense there:

```js
{ "command": "reopen_last_file", "caption": "Reopen Last Tab" },
```

Just bind that to a key and it should work fine.

**Comment by TheSavior** [comment]
Nice, thanks.
