### ISSUE TITLE
New Function: Multiline Tab bar feasible?

### ISSUE THREAD

**Issue by XIIZQ** [facelessuser/TabsExtra#30]
Hello,
is a Multiline Tabbar feasible like this?
![ftprevious 1](https://cloud.githubusercontent.com/assets/9036121/12616070/7e0c5e20-c509-11e5-9aac-686c84fdc149.png)

**Comment by facelessuser** [comment]
If I tried to do something like this it would be a hack and no doubt have some issues.   At the moment,  I have no interest in working on such a feature. This should be implemented in the core Sublime code if it was added:  not a plugin. 

With that said, I have seen this https://forum.sublimetext.com/t/multi-line-tabbar-for-st2/12978.  Maybe You can adapt it for ST3 for yourself.  I have no idea how well or  how poorly it may work, but maybe it can help you achieve what you want.
