### ISSUE TITLE
Do not show dialog if all tabs saved

### ISSUE THREAD

**Issue by mctep** [facelessuser/TabsExtra#32]
Hello! Thank you for your plugin. It is really useful.

Is it possible to do not show dialog "Are you sure you want to dismiss all targeted unsaved buffers?" if all my tabs are saved at https://github.com/facelessuser/TabsExtra/blob/5451f6d6b54c18fb96fe8ad4226d9d879183f022/tabs_extra.py#L521?

I bind `TabsExtra` command to default close tab shortcut (so I no longer need to use mouse 👍 ):

```json
	{ "keys": ["super+w"],
		"command": "tabs_extra_close_menu",
		"args": {
			"mode": "dismiss_unsaved",
			"close_type": "single"
		}
	}
```

But If I try to close my saved tab it asks me about unsaved buffers.

**Comment by mctep** [comment]
Ha! But in my case it breaks close behaviour for sticky tabs.

**Comment by facelessuser** [comment]
How does it break sticky tabs?

**Comment by facelessuser** [comment]
I think it all depends on how you use sticky tabs.  I often use then as a one shot sticky to just protect against the next mass closing.  But you can force them to remain until you manually unsticky them via https://github.com/facelessuser/TabsExtra/blob/master/tabs_extra.sublime-settings#L5.

**Comment by mctep** [comment]
Oh, excuse me... I did understand sticky behaviour incorrectly. I expect that sticky tabs should not close even when I close it in single mode. It ok! I made a mistake.

**Comment by facelessuser** [comment]
Hmm. I think I probably allow it because you are purposely trying to close a specific tab.  I guess I figured, even if it was a sticky, that you are specifically running close on that specific tab, you probably really want that tab closed.  I mean, I guess I could make it resistant to even targeted single tab closures, but I guess I figured that would be annoying.  If that is what people want, I could probably do it.  I'd have to run through all the overrides to make sure it is possible.  I know I can't intercept all closes, so in the end, I think there is a single close command I don't override because I have to use it to get Sublime's API to close a file.

**Comment by mctep** [comment]
There are no problems with closing sticky tabs. Please forget about my second comment :-) Excuse me.

Problem is that when I close tabs or single tab with `TabsExtra` commands it asks me about unsaved changes even when all my tabs are saved.

Let me tell you about my case. May be I chose wrong way to solve my little problem.

Without `TabsExtra` plugin:
1) I open file
2) Make some changes
3) Close tab with `super+w`
4) Get standart ST dialog:
![screen shot 2016-05-20 at 19 02 00](https://cloud.githubusercontent.com/assets/1949681/15434141/2c578820-1ebe-11e6-8f2e-6489519782be.png)
5) For closing dialog I take a mouse and click to `Don't Save Changes` button

I have not found way to do `5` point only with keyboard and without mouse.

When I using `TabsExtra` plugin:
0) I redefine standard key binding `super+w` to call `tabs_extra_close_menu(mode="dismiss_unsaved", close_type="single")`
1—3) The same points
4) Get `TabsExtra` dialog:
  ![screen shot 2016-05-20 at 19 16 32](https://cloud.githubusercontent.com/assets/1949681/15434416/668105ca-1ebf-11e6-833f-327aafeadb78.png)
5) For closing dialog I press `Enter` key. And it is very cool!

But! If I do not make changes or I save file before closing tab I also get `TabsExtra` dialog.

**Comment by facelessuser** [comment]
Yeah, I currently ask every time to cover **if** there are saved buffers, but I don't currently calculate if there are **actually** unsaved buffers ahead of time.  Maybe in the future I can actually check.

**Comment by mctep** [comment]
If you wish I can make PR from it commit https://github.com/mctep/TabsExtra/commit/d59269dc18dccb5a66e9cecd11ba256546b6cf4e

**Comment by facelessuser** [comment]
Sure.  A pull would be nice.  It looks like it should work fine.
