### ISSUE TITLE
Tab bar jumps between current and last tab on file save

### ISSUE THREAD

**Issue by ihatemornings** [facelessuser/TabsExtra#35]
I have the "sort tabs on file save" option enabled (love it!) and have noticed what seems to be a bug:

1. Have enough tabs open that the tab bar scrolls horizontally
2. Hit &#8984;-S multiple times
3. With each save the tab bar scrolls. First it's centred on the current tab, then scrolled all the way to the right. If you have one of the rightmost files open it jumps left instead (to an arbitrary but consistent position).

**Comment by ihatemornings** [comment]
I'm using the Package Manager install of TabsExtra, version 1.5.0.

**Comment by facelessuser** [comment]
Unfortunately I don't think I can control how Sublime scrolls the tab bar.
