### ISSUE TITLE
Don't understand upgrade message

### ISSUE THREAD

**Issue by Gabriel-p** [facelessuser/TabsExtra#37]
I just got the latest upgrade for the package, and it says:

```

Menu format upgraded to version (1.6.0). To pick up these changes, do one of the
following:

1. If using the override menu, select "Preferences->Package Settings->TabsExtra->Install/Upgrade Default Override Menu"
   from Sublime's menu.

2. If using the default menu, select "Preferences->Package Settings->TabsExtra->Install/Upgrade TabsExtra Menu"
   from the menu" from Sublime's menu.
```

I've no idea what menu I am using. What are the "override menu" and "default menu" options? Which of the above directions should I follow?

**Comment by facelessuser** [comment]
This is covered in the documents: http://facelessuser.github.io/TabsExtra/usage/#installupgrade-menu.

**Comment by Gabriel-p** [comment]
Got it, sorry, I should've RTFD first.
