### ISSUE TITLE
TabsExtra keeps notifying about update, even after being dismissed several times

### ISSUE THREAD

**Issue by Ardethian** [facelessuser/TabsExtra#38]
I got a tab telling me that TabsExtra has been updated. 
All is fine, but after I close it, it keeps popping up whenever I'm starting Sublime Text again. 
Even if I don't close the tab itself, it will open a different tab again the next time I run ST.

It happens both on my work computer and home computer, so I doubt its an individual thing.

I capped a short gif to illustrate it - http://i.imgur.com/2Ba1y5I.gifv

**Comment by facelessuser** [comment]
Did you do what it asked?

**Comment by Ardethian** [comment]
Forgive me. I'm stupid.

Thanks. :)

**Comment by facelessuser** [comment]
No problem :smile:.
