### ISSUE TITLE
Duplicate - option doesn't work...

### ISSUE THREAD

**Issue by PixelT** [facelessuser/TabsExtra#40]
![](http://image.prntscr.com/image/f28b361f839f4a24b5a42c5f585788c9.png)

After click that option, the address bar for the path to file copy will show, but after change / write the proper path and accept it by Enter, the duplicate files doesn't created.

**Comment by facelessuser** [comment]
You will have to provide more information for support.  `Duplicate` works for me just fine.

**Comment by PixelT** [comment]
For simple project (where the path to files isn't long) the duplicate option work ok.
But in magento - where are much longer path to files, for example:
``/Applications/XAMPP/xamppfiles/htdocs/project-test/app/design/frontend/my-template/default/template/checkout/cart/minicart.phtml``
the options didn't duplicate the file

**Comment by facelessuser** [comment]
I will try a longer path, but I can't promise I will be able to reproduce. I use duplicate all the time, even in big projects, but I will try to reproduce.  Maybe the hyphen is a problem?  I'll check.

**Comment by facelessuser** [comment]
Closing as a stale issue. I wasn't able to reproduce, but I'll see if anyone reopens a similar issue. If so, I may take a look again.
