### ISSUE TITLE
Is this what the context menu should look like?

### ISSUE THREAD

**Issue by webbexpert** [facelessuser/TabsExtra#41]
Appears different than the site -- can't figure out how to use the sticky tabs (not available in the list of options)
Thoughts? Thanks in advance!
![image](https://cloud.githubusercontent.com/assets/6935487/19217954/792858dc-8d9f-11e6-9b51-b32d925478eb.png)

**Comment by facelessuser** [comment]
No, that makes me think it hasn't done everything yet it is supposed to.  Did you run follow these initial steps: http://facelessuser.github.io/TabsExtra/usage/#installupgrade-menu?

**Comment by facelessuser** [comment]
No further response for 21 days.  I'll give this a week and then close this.

**Comment by evandrocoan** [comment]
>TabsExtra allows users to make a tab sticky. This allows the tab to not close when a bulk close operation is performed. By default, after any close command is run, the sticky tab properties are forgotten. You can make a tab’s stickiness persist by enabling persistent_sticky.

>    // By default TabsExtra forgets a tab's "stickiness" when
    // any "tab close" command is issued.  You can make the tab's
    // "Stickiness" persist by enabling the following feature.
    "persistent_sticky": false,

May the sticky tabs be like `resistant` to the close button also?

The package https://github.com/DavidGerva/LockTab-Sublime-Plugin does it but it us kinda broken:

1. https://github.com/DavidGerva/LockTab-Sublime-Plugin/issues/1`

But stills not compatible with this built in sticky, as once you trigger the close all command it try also to close the Locked Tab by the other package.

**Comment by facelessuser** [comment]
Thanks for the suggestion.  This twist is not really related to this issue.  Please open a new issue and describe the feature request in as much detail as possible. Thanks!
