### ISSUE TITLE
Tab focusing

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/TabsExtra#44]
Somewhere along the way Sublime's tab focus logic changed a bit.  At times, tab focusing when clicking a file in the sidebar has gotten weird with TabsExtra, and it needs some investigation as it's getting on my nerves.  If I'm lucky, I can just remove the current workaround, if not, the workaround could get more complicated or at least need changes.

**Comment by SCdF** [comment]
It would be ideal if we could just disable TabsExtra's focus management completely ("fallback_focus": "default") or something like that. I too find the current interaction pretty weird, with it sometimes doing what I'd expect, but often focusing on something else entirely. I think ST's default logic is fine.

**Comment by facelessuser** [comment]
If you are using any feature that requires to know the last active tab, ST's default logic makes it impossible to accurately detect the last active tab.  This is why we have such a convoluted situation here.  I have to jump through hoops to determine when someone is dragging a tab etc.

I haven't decided what I am going to do yet as I haven't had time to look at this yet, but once I do I will either (A) Fix the logic so it works better or (B) remove it entirely and people who wish to for the last active tab to be known will just have to accept that is not reliably possible.

**Comment by SCdF** [comment]
Ahh, makes sense. With the exception of Reopen tab[1] I didn't know there were features that require that you know the last active tab.

[1] Which seems to be the same as the native Reopen Closed File?

**Comment by facelessuser** [comment]
> Which seems to be the same as the native Reopen Closed File?

Probably, I'd have to look.

In general, all this last active tab stuff is an elaborate hack.  At the time, I was able to more accurately detect the last active tab in most corner cases, but later I discovered some weird focus side effects.  Maybe it is possible I can adjust my current logic to get the same information without doing what I am currently doing, but maybe not.

There is clearly a problem, enough to make me create this issue. Hopefully some time soon I can carve out some time to properly evaluate what is going on here, but I do support  a lot of repos, and I prioritize it by what annoys me the most.  Sadly, other things have just been more important to me so far.

**Comment by facelessuser** [comment]
ST4 has become even harder to have a fallback focus. I'm considering abandoning this. It will simplify a lot of things as well. I'm just tired of fighting this. I tried to work on this today to finally fix it, but I'm just not interested in fighting this anymore.

I'd rather add a command that can just find the last active tab and focus when you feel like you want it. Right now, you are fighting Sublime events, and there are so many race conditions. ST4 behaves different and can now have multi-previews.

**Comment by facelessuser** [comment]
We are killing focus features, both on spawn/open and on close. We are also limiting save on sort to only when `preview_on_click` (Sublime's setting) is `false`. No more fighting focus issues and the sidebar.
