### ISSUE TITLE
Sort on activation by activation date

### ISSUE THREAD

**Issue by franciscolourenco** [facelessuser/TabsExtra#45]
When a tab is activated is should be moved to the first position.
Is this possible?

**Comment by facelessuser** [comment]
I believe it currently sorts by (whatever you choose) on save.  It's not really practical in 99% of the cases to sort on activation.  Only when you want to sort by activated would it make sense to sort on activation (but I do at least understand why in this one case it would be desirable to sort on activation).

Let me think about this one.

**Comment by aristidesfl** [comment]
Any progress on this? thanks!

**Comment by facelessuser** [comment]
Nope. I am very busy, and support a number of repositories.  This is low priority, so I'll have to see when I get some time to look at this and make a decision.

**Comment by facelessuser** [comment]
This is going to be messy. I won't promise anything, but I'll look into it.  There are a number of complications to pull this off.

- Sorting activates windows as it is sorting, so we will have to watch for this, this is probably pretty easy to avoid if things were complicated by the next issue.
- Moving tabs:  there are already tricks to detect moving and focusing last activated tab after move, and also ignoring the original fallback tab to the left after deletion.  Then we have to add in more complexity to then sort them.

Maybe there is something I can clean up to make this easier, but currently...ughh.  I've got some stuff to figure out, so though on the surface it seemed trivial enough, it isn't.

**Comment by facelessuser** [comment]
Not only that, playing sort on activation creates awkward tag dragging as we are injecting a sort as we are activating the tab when attempting to drag.  There are ways around this, but it just further complicates the code. I'm iffy on this feature now that I am seeing the complications that I have to work around.  I'm not sure if the payoff is worth it, but I will update this issue with any developments or decisions I have in regards to it.
