### ISSUE TITLE
Cannot close new views, as the Find Results

### ISSUE THREAD

**Issue by evandrocoan** [facelessuser/TabsExtra#49]
I was trying to close the `Find Results` view with `Ctrl+W`, it was not working. Then I enabled the debug command:
```
>>> sublime.log_input(True); sublime.log_commands(True); sublime.log_result_regex(True)
command: drag_select {"event": {"button": 1, "x": 287.5, "y": 168.5}}
key evt: control+w
command: close
plugin rewritten command: tabs_extra_close
```
So, it should be closing or not when I press `Ctrl+W`?

**Comment by evandrocoan** [comment]
Not sure why, but after restarting Sublime Text it started working again.

It happened right after enabling the package `AdvancedNewFile`, with the issue:

1. https://github.com/skuroda/Sublime-AdvancedNewFile/issues/169 TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by facelessuser** [comment]
I do override the close command, but like you found, it works for me.
