### ISSUE TITLE
Add preferences entry to command pallet

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/TabsExtra#53]
Most packages provide an entry to plugin settings in the command pallet. It's the easiest way to realize and/or find them.

```
    {
        "caption": "Preferences: TabsExtra Settings",
        "command": "edit_settings",
        "args": {
            "base_file": "${packages}/TabsExtra/tabs_extra.sublime-settings",
            "default": "{\n$0\n}\n"
        }
    }
```

**Comment by facelessuser** [comment]
I wouldn't say most, but there may be some.  Though this has been requested before, and is on my list, I just haven't gotten around to it.
