### ISSUE TITLE
Update message shows up every time on Sublime' start up.

### ISSUE THREAD

**Issue by shermendev** [facelessuser/TabsExtra#54]
I see this message every time I open Sublime Text 3, kinda annoying, how do I prevent it from showing up?

![capture](https://user-images.githubusercontent.com/23652557/32991917-4d1346dc-cd4d-11e7-90af-dd32840358e7.PNG)

**Comment by facelessuser** [comment]
Please read the message and upgrade your menu and it should go away. Until the menu format matches the new released menu format, it will keep popping up.

**Comment by shermendev** [comment]
My bad, thanks for a quick answer 😅

**Comment by 4sStylZ** [comment]
Strange way to show a message like that. I am here for the same reason. I wasn’t understanding that the message wasn’t a upgrade package message (In fact I have disabled theses message by destroying the code who show it lol)

Very annoying and after read it I doesn’t understand what is the implication of choose the first or second option.

By the way, choosing one hide this message.
Bye.

**Comment by vongoh** [comment]
Right, I came by here because I'm wondering what the difference is between "TabsExtra Menu".  And 'Default Overide Menu'.    And if I don't choose one the message won't go away.

Choices!  Hmmmm...

**Comment by facelessuser** [comment]
You guys realize this is covered in the documentation, right? http://facelessuser.github.io/TabsExtra/#installupgrade-menu

You the menu can be out of date with the API, so it keeps telling you as things probably aren't going to work right unless you upgrade.  Sometimes it is less severe and you won't pick up a new command unless you upgrade.

**Comment by facelessuser** [comment]
I'll probably update the message to be more clear.

**Comment by Narretz** [comment]
How do I need which of "Basic" and "Override" I'm currently using?

**Comment by facelessuser** [comment]
If all your close items are grouped and ordered in a sane manner, you are probably using the override.  Without overriding, TabsExtra cannot force the close options to all be grouped together.

**Comment by facelessuser** [comment]
Also, Basic and Override menu description is covered in the documentation: http://facelessuser.github.io/TabsExtra/#installupgrade-menu.

**Comment by facelessuser** [comment]
Message should be a bit more clear in the next release
