### ISSUE TITLE
[Feature request] Minimize tabs

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/TabsExtra#55]
### 1. Request

It would be nice, if you add a new feature — minimize tabs; as Firefox feature «[**Pinned Tabs**](https://support.mozilla.org/en-US/kb/pinned-tabs-keep-favorite-websites-open)»:

![Pinned tabs](https://i.imgur.com/27inpGl.png)

In Firefox sticky tab minimize.

### 2. Justification

TabsExtra users can sticky tabs. But the size of the tabs persists. Tabs take the place in width of the screen and can interfere for users, especially if users divide the screen into windows or panes.

For example, I sticky files with my journal (`2018.jernl`) and TODO (`2018.todo`). I use it every days.

1. If I close and/or not stick this tabs, I need often open files. It can take a lot of time.
1. If I don't close and/or stick this tabs, these tabs will interfere me, when I'm doing other things in Sublime Text.

Thanks.

**Comment by facelessuser** [comment]
There just isn't any API that allows you to change tab sizes.  I think it is a cool idea, but it just isn't practical.  I'd have to change the tab name which would then make your hover not show the real title.  It wouldn't be very useful.  If Sublime ever allows us to directly change a Tab's size, I'd be willing to reconsider.

**Comment by facelessuser** [comment]
Closing as there is no actionable item.
