### ISSUE TITLE
"Copy File Path" menu not working

### ISSUE THREAD

**Issue by bk800** [facelessuser/TabsExtra#68]
My OS: Windows 10 Pro 64-bit

With the new Sublime Text build "4180", the "Copy File Path" menu stopped working.
This includes "File Name", "Full Path", and "File URI".

**EX**: 
Before, using "File URI" would set the clip board to "file:///[path to file]".
Now I see "file:///[whatever was in the windows clip board before selecting 'File URI']"

If I uninstall build 4180 and re-install build 4143, the "Copy File Path" menus work again.

**Comment by facelessuser** [comment]
Well, that makes me unhappy 😦. Thanks for pointing this out. It may be there is a bug in Sublime, but I'll have to take some time and investigate more.

**Comment by bk800** [comment]
Thanks! Appreciate it.  I'm using these features all the time.

**Comment by facelessuser** [comment]
It seems that Sublime's built-in `copy_path` command now uses a Window instead of a View. I'm not sure exactly when this change was introduced though. I have a fix, I just have to narrow down what build it changed.

**Comment by facelessuser** [comment]
Turns out it was dev release 4170

**Comment by facelessuser** [comment]
I should have a fix released this weekend.

**Comment by bk800** [comment]
Its working great!   Thanks a ton!
